<template>
    <div>
        <div v-if="pageName!=''">
            <h1>{{ pageName }}</h1>
            <br>
        </div>

        <div v-if="pageDes!=''">
            <p>{{ pageDes }}</p>
            <br>
        </div>
        
        <div v-if="methodType!='' && pathURL!=''">
            <div>
                <code>Method : {{ methodType }}</code>
            </div>
            <div>
                <code>Path : {{ urlAPI }}/{{ pathURL }}</code>
            </div>
            <br>
        </div>
        
        <CardCustom :header="headerReq" :textArea="textAreaReq" :fields="fieldsCommon" :items="itemsReq"/>
        <br><br>

        <CardCustom :header="headerRes" :textArea="textAreaRes" :fields="fieldsCommon" :items="itemsRes"/>
        <br><br>

        <CardCustom :header="headerErr" :fields="fieldsErr" :items="itemsErr"/>
        
    </div>
</template>

<script>
import CardCustom from '../../components/CardCustom.vue'
import Methods from '../../methods'
export default {
    components: {
        CardCustom
    },

    data(){
        return {
            pageName: "Verify Session",
            pageDes: "Use for Operater Verify Session",
            methodType: "POST",
            urlAPI: `{${process.env.VUE_APP_OPERATER_URL_API}}`,
            pathURL: "verifySession",

            headerReq: 'Request Body',
            textAreaReq: "",
            fieldsCommon: [
                { key: 'name', label: 'Name' },
                { key: 'type', label: 'Type' },
                { key: 'mandatory', label: 'Mandatory' },
                { key: 'example', label: 'Example Value' },
                { key: 'des', label: 'Description' }
            ],
            itemsReq: [
                { 
                    name: 'token', 
                    type: 'string',
                    mandatory: 'Y',
                    example: 'e6c49dd6f6d6333367e43b5f1c1173c8',
                    des: 'Token generated by operator.'
                },
                { 
                    name: 'requestID', 
                    type: 'string',
                    mandatory: 'Y',
                    example: '202112311000000001',
                    des: 'YYYYDDMM+<API ID(01)>+<running number 9 digits>'
                },
                { 
                    name: 'agentID', 
                    type: 'string',
                    mandatory: 'Y',
                    example: 'XXXX',
                    des: 'ID of agent.'
                },
                { 
                    name: 'key', 
                    type: 'string',
                    mandatory: 'Y',
                    example: '',
                    des: ''
                }
            ],

            headerRes: 'Response',
            textAreaRes: "",
            itemsRes: [
                { 
                    name: 'code', 
                    type: 'string',
                    mandatory: 'Y',
                    example: '0000',
                    des: ''
                },
                { 
                    name: 'description', 
                    type: 'string',
                    mandatory: 'Y',
                    example: 'success',
                    des: ''
                },
                { 
                    name: 'memberID', 
                    type: 'string',
                    mandatory: 'Y',
                    example: 'member01',
                    des: 'Create new member if does not exist at provider side.'
                },
                { 
                    name: 'balance', 
                    type: 'decimal',
                    mandatory: 'Y',
                    example: '10000',
                    des: ''
                }
            ],

            headerErr: 'Error Code',
            fieldsErr: [
                { key: 'val', label: 'Value' },
                { key: 'des', label: 'Description' }
            ],
            itemsErr: [
                { val: '0000', des: 'Success' },
                { val: '9900', des: 'System cannot process this request at the moment. Please try again later' },
                { val: '9902', des: 'Internal Server Error' }
            ]

        }
    },

    created() {
        this.textAreaReq = Methods.convertDataToJsonFormat(this.itemsReq, "");
        this.textAreaRes = Methods.convertDataToJsonFormat(this.itemsRes, "object");
    },

    methods: {
        
    }
}
</script>

<style scoped>

</style>