<template>
    <div>
        <div v-if="pageName!=''">
            <h1>{{ pageName }}</h1>
            <br>
        </div>

        <div v-if="pageDes!=''">
            <p>{{ pageDes }}</p>
            <br>
        </div>
        
        <div v-if="methodType!='' && pathURL!=''">
            <div>
                <code>Method : {{ methodType }}</code>
            </div>
            <div>
                <code>Path : {URL-API}{{ pathURL }}</code>
            </div>
            <br>
        </div>
        
        <CardCustom :header="headerReq" :textArea="textAreaReq" :fields="fieldsCommon" :items="itemsReq"/>
        <br><br>

        <CardCustom :header="headerRes" :textArea="textAreaRes" :fields="fieldsCommon" :items="itemsRes"/>
        <br><br>

        <CardCustom :header="headerErr" :fields="fieldsErr" :items="itemsErr"/>
        
    </div>
</template>

<script>
import CardCustom from '../../components/CardCustom.vue'
export default {
    components: {
        CardCustom
    },

    data(){
        return {
            pageName: "Join Game",
            pageDes: "Use for Partner Join Game",
            methodType: "POST",
            pathURL: "/joinGame",

            headerReq: 'Request Body',
            textAreaReq: "",
            fieldsCommon: [
                { key: 'name', label: 'Name' },
                { key: 'type', label: 'Type' },
                { key: 'mandatory', label: 'Mandatory' },
                { key: 'example', label: 'Example Value' },
                { key: 'des', label: 'Description' }
            ],
            itemsReq: [
                { 
                    name: 'token', 
                    type: 'string',
                    mandatory: 'Y',
                    example: 'e6c49dd6f6d6333367e43b5f1c1173c8',
                    des: 'Token generated by operator.'
                },
                { 
                    name: 'gameID', 
                    type: 'int',
                    mandatory: 'Y',
                    example: '11001',
                    des: ''
                },
                { 
                    name: 'language', 
                    type: 'string',
                    mandatory: 'Y',
                    example: 'EN',
                    des: 'EN,TH,CN'
                },
                { 
                    name: 'homeURL', 
                    type: 'string',
                    mandatory: 'N',
                    example: 'www.google.com',
                    des: 'URL redirect to when the player logout.'
                },
                { 
                    name: 'agentID', 
                    type: 'string',
                    mandatory: 'Y',
                    example: 'XXXX',
                    des: 'ID of agent'
                },
                { 
                    name: 'key', 
                    type: 'string',
                    mandatory: 'Y',
                    example: '',
                    des: ''
                }
            ],

            headerRes: 'Response',
            textAreaRes: "",
            itemsRes: [
                { 
                    name: 'code', 
                    type: 'string',
                    mandatory: 'Y',
                    example: '0000',
                    des: ''
                },
                { 
                    name: 'description', 
                    type: 'string',
                    mandatory: 'Y',
                    example: 'success',
                    des: ''
                },
                { 
                    name: 'URL', 
                    type: 'string',
                    mandatory: 'Y',
                    example: '',
                    des: ''
                }
            ],

            headerErr: 'Error Code',
            fieldsErr: [
                { key: 'val', label: 'Value' },
                { key: 'des', label: 'Description' }
            ],
            itemsErr: [
                { val: '0000', des: 'Success' },
                { val: '9900', des: 'System cannot process this request at the moment. Please try again later' },
                { val: '9902', des: 'Internal Server Error' }
            ]

        }
    },

    created() {
        this.textAreaReq = this.convertDataToJsonFormat(this.itemsReq, "");
        this.textAreaRes = this.convertDataToJsonFormat(this.itemsRes, "response");
    },

    methods: {
        convertDataToJsonFormat(data, typeJson){
            let jsonFormat = "";
            let spaceInit = 2;
            if(data.length!=0){
                jsonFormat = "{\n";
                data.forEach((it, id) => {
                    jsonFormat += `${this.addSpace(spaceInit)}"${it.name}": "${it.example}"`;

                    if(data.length>(id+1)){
                        jsonFormat += ",\n";
                    }

                    if(typeJson=="response" && id==1){
                        jsonFormat += `${this.addSpace(spaceInit)}"data":  {\n`;
                        spaceInit = 8;
                    }
                });

                if(typeJson=="response"){
                    jsonFormat += `\n${this.addSpace(2)}}`;
                }
                
                jsonFormat += "\n}";
            }

            console.log(jsonFormat);

            return jsonFormat;
        },

        addSpace(number){
            let space = ""
            for (let index = 0; index < number; index++) {
                space += " ";
            }
            return space
        }
    }
}
</script>

<style scoped>

</style>